### ISSUE TITLE
Quoter button/icon not displaying

### ISSUE THREAD

**Issue by SilverlightPony** [samogot/betterdiscord-plugins#37] opened 2018-06-30 05:25 UTC
Noticed a few days ago that the Quoter button/icon had stopped appearing.  At first I thought Quoter had stopped working altogether, but later realized the plugin was still working aside from that icon.

Reinstalling both BandagedBD and Quoter had no effect.

**Comment by intrnl** [comment] 2018-06-30 05:54
Duplicate of issue #36

**Comment by samogot** [comment] 2018-06-30 08:28
Fixed with lib v1.11

**Closed by samogot** 2018-06-30 08:28 UTC
